version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - 7870:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama3
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 10 && ollama run llama3.2:1b"]
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false
